[Compressor]
AmbientPressure = 100 #Inlet Pressure [kPaA] Total Pressure
AmbientTemperature = 298 #Inlet Temperature in K
Weight = 0.1 #kg
Inertia = 0.1 #kgm2
gamma = 1.395
Flow = 0.8 #kg/s Flow Target
PRC = 5.0 #Pressure Ratio Target
BleedRatio = 0.1 #Ratio of compressor flow bleed

[Combustor]
CombustionTemp_T1t = 1473 #Combustion Temp in K
CombustordeltaP= 0.1 #Ratio Inlet Pres.loss
AirFuelRatio = 40 #kg/kg
FuelLatentHeatLHV = 38 #MJ/kg
TempEfficiency = 1.0 #Actual Temp vs Theoretical Temp

[Turbine]
Weight = 0.1 #kg
Inertia = 0.1 #kgm2
BackPressure = 110 #Turbine outlet Initial backpressure [kPaA] Static Pressure
BleedRatio = 0.0 #Ratio of turbine flow bleed

[Shaft]
Weight = 0.1 #kg
Inertia = 0.1 #kgm2
MechLoss = 0.05 #Mechanical Power Loss %

[Calculation]
Step = 100 #rpm resolution for calculation convergence[rpm]
PowRes = 3 #Target Power Resolution for calculation convergence[kW]
PRCRes = 0.01 #PRC Resolution for calculation convergence
WtRes = 0.1 #Wt* Resolution for calculation convergence