[Compressor]
"Power[kW]" = 203.308
"Speed RPM" = 48600.0
"Outlet Pres[kPaA]" = 499.458
"Outlet Temp[degC]" = 281.943
"Pres Ratio PRC" = 4.995
"Comp Efficiency" = 0.669
"Air Flow[kg/s]" = 0.8
"Turbine Pressure Ratio" = 1.053

[Turbine]
"Enthalpy[kW]" = 229.444
"Turbine Power[kW]" = 214.009
"Speed RPM" = 48600.0
"Inlet Pres.[kPa]" = 474.485
"Inlet Temp[C]" = 1300.0
"Outlet Pres[kPa]" = 110.0
"Outlet Temp[degC]" = 931.71
"Pres Ratio PRT" = 4.314
"Turb Efficiency" = 0.656
"Turbine Flow[kg/s]" = 0.496
"Bypass Ratio" = 0.114

[Shaft]
"Fuel Flow [kg/s]" = 0.016
"Turbine Required Flow[kg/s]" = 0.44
"Turbine Map Flow[kg/s]" = 0.462
"Theoretical T1t[degC]" = 1522.013
