[Compressor]
"Power[kW]" = 246.704
"Speed RPM" = 51200.0
"Outlet Pres[kPaA]" = 498.734
"Outlet Temp[degC]" = 274.425
"Pres Ratio PRC" = 4.987
"Comp Efficiency" = 0.688
"Air Flow[kg/s]" = 1.0
"Turbine Pressure Ratio" = 1.053

[Turbine]
"Enthalpy[kW]" = 55.346
"Turbine Power[kW]" = 259.689
"Speed RPM" = 51200.0
"Inlet Pres.[kPa]" = 473.797
"Inlet Temp[C]" = 1300.0
"Outlet Pres[kPa]" = 110.0
"Outlet Temp[degC]" = 1214.715
"Pres Ratio PRT" = 4.307
"Turb Efficiency" = 0.152
"Turbine Flow[kg/s]" = 0.517
"Bypass Ratio" = -3.457

[Shaft]
"Fuel Flow [kg/s]" = 0.017
"Turbine Required Flow[kg/s]" = 2.303
"Turbine Map Flow[kg/s]" = 0.814
"Theoretical T1t[degC]" = 1514.495
