[Compressor]
"Power[kW]" = 28.0
"Speed RPM" = 112000.0
"Outlet Pres" = 292.433
"Outlet Temp" = 166.479
"Pres Ratio PRC" = 2.924
"Comp Efficiency" = 0.747
"Air Flow[kg/s]" = 0.2
"Turbine Pressure Ratio" = 1.053

[Turbine]
"Enthalpy[kW]" = 35.162
"Turbine Power[kW]" = 29.474
"Speed RPM" = 112000.0
"Inlet Pres.[kPa]" = 277.812
"Inlet Temp[K]" = 1273.15
"Outlet Pres[kPa]" = 110.0
"Outlet Temp[K]" = 859.843
"Pres Ratio PRT" = 2.526
"Turb Efficiency" = 0.477
"Turbine Flow[kg/s]" = 0.21
"Bypass Ratio" = 0.204

[Shaft]
"Fuel Flow [kg/s]" = 0.01
"Turbine Required Flow[kg/s]" = 0.167
"Turbine Map Flow[kg/s]" = 0.08
"Theoretical T1t" = 2270.209
