[Compressor]
Weight = 0.1 #kg
Inertia = 0.1 #kgm2
gamma = 1.395

[Combustor]
FuelLatentHeatLHV = 38 #MJ/kg

[Turbine]
Weight = 0.1 #kg
Inertia = 0.1 #kgm2

[Shaft]
Weight = 0.1 #kg
Inertia = 0.1 #kgm2
MechLoss = 0.05 #Mechanical Power Loss %

[Calculation]
Step = 10 #rpm resolution for calculation convergence[rpm]
PowRes = 0.2 #Target Power Resolution for calculation convergence[kW]
PRCRes = 0.001 #PRC Resolution for calculation convergence
WtRes = 0.2 #Wt* Resolution for calculation convergence