[Compressor]
Weight = 0.1 #kg
Inertia = 0.1 #kgm2
gamma = 1.395
Flow = 0.8 #kg/s Flow Target
PRC = 5.0 #Pressure Ratio Target
BleedRatio = 0.4 #Ratio of compressor flow bleed

[Combustor]
CombustionTemp_T1t = 1300 #degC
CombustordeltaP= 0.05 #Ratio Inlet Pres.loss
AirFuelRatio = 30 #kg/kg
FuelLatentHeatLHV = 38 #MJ/kg

[Turbine]
Weight = 0.1 #kg
Inertia = 0.1 #kgm2
BackPressure = 110 #Turbine outlet Initial backpressure [kPaA]
BleedRatio = 0 #Ratio of turbine flow bleed

[Shaft]
Weight = 0.1 #kg
Inertia = 0.1 #kgm2
MechLoss = 0.05 #Mechanical Power Loss %

[Calculation]
Step = 100 #rpm resolution for calculation
PowRes = 10 #Target Power Resolution [kW]
PRCRes = 0.02 #PRC Resolution
