[Compressor]
AmbientPressure = 100 #Inlet Pressure [kPaA] Total Pressure Pc_in
AmbientTemperature = 298 #Inlet Temperature in K Yc_in
Flow = 0.8 #kg/s Flow Target Wc_in
PRC = 5.0 #Pressure Ratio Target PRC
BleedRatio = 0.11 #Compressor Bleed Ratio

[Combustor]
CombustionTemp_T1t = 1473 #Combustion Temp in K T1t_th
CombustordeltaP= 0.15 #Ratio Inlet Pres.loss CB_dp
AirFuelRatio = 40 #kg/kg AFR
TempEfficiency = 1.0 #Actual Temp vs Theoretical Temp TempEff
BleedRatio = 0.0 #Turbine Bleed Ratio

[Turbine]
BackPressure = 140 #Turbine outlet Initial backpressure [kPaA] Total Pressure Pt_out
